# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02_sequences/03_find-and-permute/02_find.ipynb.

# %% auto #0
__all__ = ['find', 'find_if', 'find_if_not', 'find_mismatch', 'find_adjacent_mismatch', 'count_if', 'all_of', 'any_of', 'none_of']

# %% ../../nbs/02_sequences/03_find-and-permute/02_find.ipynb #396adc47
def find(arr, target):
    index = 0
    for value in arr:          # iterator walk
        if value == target:    # equality
            return index       # found
        index = index + 1
    return -1                  # not found

# %% ../../nbs/02_sequences/03_find-and-permute/02_find.ipynb #42cdd1cb
def find_if(a, first, last, pred):
    for i in range(first, last):
        if pred(a[i]):
            return i
    return last

# %% ../../nbs/02_sequences/03_find-and-permute/02_find.ipynb #b3e5b809
def find_if_not(a, first, last, pred):
    for i in range(first, last):
        if not pred(a[i]):
            return i
    return last

# %% ../../nbs/02_sequences/03_find-and-permute/02_find.ipynb #ec529ad2
def find_mismatch(a, f0, l0, b, f1, l1, r):
    while f0 != l0 and f1 != l1 and r(a[f0], b[f1]):
        f0 += 1
        f1 += 1
    return f0, f1

# %% ../../nbs/02_sequences/03_find-and-permute/02_find.ipynb #6750a67d
def find_adjacent_mismatch(a, first, last, pred):
    if first == last:
        return last
    x = a[first]
    first += 1
    while first != last and pred(x, a[first]):
        x = a[first]
        first += 1
    return first

# %% ../../nbs/02_sequences/03_find-and-permute/02_find.ipynb #23285138
def count_if(a, first, last, pred):
    count = 0 
    for i in range(first, last):
        if pred(a[i]):
            count += 1
    return count

# %% ../../nbs/02_sequences/03_find-and-permute/02_find.ipynb #94fb16a1
def all_of(a, first, last, pred): 
    return find_if_not(a, first, last, pred) == last    

# %% ../../nbs/02_sequences/03_find-and-permute/02_find.ipynb #662eee4c
def any_of(a, first, last, pred):
    return find_if(a, first, last, pred) != last

# %% ../../nbs/02_sequences/03_find-and-permute/02_find.ipynb #39ad0506
def none_of(a, first, last, pred):
    return find_if(a, first, last, pred) == last
