"""Docs: https://gophry.github.io/programming-first-principles/02_sequences/03_algorithms-101/partition.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02_sequences/03_algorithms-101/04_partition.ipynb.

# %% auto #0
__all__ = ['partition_single_pass', 'partition_two_pointer', 'is_partitioned', 'partition_point_linear']

# %% ../../nbs/02_sequences/03_algorithms-101/04_partition.ipynb #5da32fb5
from .rearrange import swap
def partition_single_pass(a, pred):
    n = 0
    for i in range(len(a)):
        if pred(a[i]):
            if n != i:
                swap(a, n, i)
            n += 1
    return n

# %% ../../nbs/02_sequences/03_algorithms-101/04_partition.ipynb #fd13dc06
from .rearrange import swap
def partition_two_pointer(a, pred):
    lo, hi = 0, len(a) - 1
    while lo <= hi:
        if pred(a[lo]):
            lo += 1
        else:
            if not pred(a[hi]):
                hi -= 1
            else:
                swap(a, lo, hi)
                lo += 1
                hi -= 1
    return lo

# %% ../../nbs/02_sequences/03_algorithms-101/04_partition.ipynb #840f00c3
from .find import find_if, find_if_not

def is_partitioned(a, first, last, pred):
    i = find_if_not(a, first, last, pred)
    j = find_if(a, i, last, pred )
    return j == last

# %% ../../nbs/02_sequences/03_algorithms-101/04_partition.ipynb #87c3437d
from .find import find_if_not
def partition_point_linear(a, first, last, pred):
    return find_if_not(a, first, last, pred)
