"""Docs: https://gophry.github.io/programming-first-principles/02_sequences/03_algorithms-101/rearrangement.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02_sequences/03_algorithms-101/03_rearrangement.ipynb.

# %% auto #0
__all__ = ['swap', 'reverse', 'reverse_py', 'rotate', 'rotate_py', 'slide']

# %% ../../nbs/02_sequences/03_algorithms-101/03_rearrangement.ipynb #904cbeee
def swap(a, i, j):
    a[i], a[j] = a[j], a[i]

# %% ../../nbs/02_sequences/03_algorithms-101/03_rearrangement.ipynb #589258da
def reverse(seq,first,last):
  """
  Reverses elements in the half-open range [f, l) using swap and iteration
  """
  last -= 1
  while first < last:
    seq[first], seq[last] = seq[last], seq[first]
    first += 1
    last -= 1

# %% ../../nbs/02_sequences/03_algorithms-101/03_rearrangement.ipynb #4fd53cd3
def reverse_py(seq, first, last):
    """Reverses elements in the half-open range [first, last) using slicing"""
    seq[first:last] = seq[first:last][::-1]

# %% ../../nbs/02_sequences/03_algorithms-101/03_rearrangement.ipynb #e8c33358
def rotate(a, first, middle, last):
    reverse(a, first, middle)
    reverse(a, middle, last)
    reverse(a, first, last)
    return first + (last - middle)

# %% ../../nbs/02_sequences/03_algorithms-101/03_rearrangement.ipynb #67e2c450
def rotate_py(a, first, middle, last):
    reverse_py(a, first, middle)
    reverse_py(a, middle, last)
    reverse_py(a, first, last)
    return first + (last - middle)

# %% ../../nbs/02_sequences/03_algorithms-101/03_rearrangement.ipynb #c83b1c81
def slide(a, f, l, p):
    if p < f:
        return p, rotate(a, p, f, l)
    if l < p:
        return rotate(a, f, l, p), p
    return f, l
