"""Docs: https://gophry.github.io/programming-first-principles/02_sequences/03_algorithms-101/rearrangement.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02_sequences/03_algorithms-101/03_rearrangement.ipynb.

# %% auto #0
__all__ = ['swap', 'reverse', 'rotate', 'slide']

# %% ../../nbs/02_sequences/03_algorithms-101/03_rearrangement.ipynb #904cbeee
def swap(a, i, j):
    a[i], a[j] = a[j], a[i]

# %% ../../nbs/02_sequences/03_algorithms-101/03_rearrangement.ipynb #589258da
def reverse(a,f,l):
  """
  Reverses elements in the half-open range [f, l)
  """
  l -= 1
  while f < l:
    a[f], a[l] = a[l], a[f]
    f += 1
    l -= 1

# %% ../../nbs/02_sequences/03_algorithms-101/03_rearrangement.ipynb #e8c33358
def rotate(a, first, middle, last):
    reverse(a, first, middle)
    reverse(a, middle, last)
    reverse(a, first, last)
    return first + (last - middle)

# %% ../../nbs/02_sequences/03_algorithms-101/03_rearrangement.ipynb #c83b1c81
def slide(a, f, l, p):
    if p < f:
        return p, rotate(a, p, f, l)
    if l < p:
        return rotate(a, f, l, p), p
    return f, l
