# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02_sequences/04_sorting/01_selection.ipynb.

# %% auto #0
__all__ = ['min_element', 'min_element_py', 'max_element', 'minmax_element', 'is_sorted_until', 'is_sorted', 'lower_bound', 'upper_bound', 'equal_range', 'binary_search', 'selection_sort', 'insertion_sort']

# %% ../../nbs/02_sequences/04_sorting/01_selection.ipynb #8c857822
from ..ordering import out_of_order

def min_element(seq, first, last):
    """
    Returns the index of the minimum element in the range [first, last).
    """
    if first == last:
        return last
    min_index = first
    for i in range(first + 1, last):
        if out_of_order(seq[min_index],seq[i]):
            min_index = i
    return min_index

# %% ../../nbs/02_sequences/04_sorting/01_selection.ipynb #d99fa235
def min_element_py(seq, first, last):
    return min(range(first, last), key=partial(getitem, seq), default=last)

# %% ../../nbs/02_sequences/04_sorting/01_selection.ipynb #da15b958
from ..ordering import in_order
def max_element(seq, first, last):
    """ 
    Returns the index of the maximum element in the range [first, last).
    """
    if first == last:
        return last
    max_index = first
    for i in range(first + 1, last):
        if in_order(seq[max_index],seq[i]):
            max_index = i
    return max_index

# %% ../../nbs/02_sequences/04_sorting/01_selection.ipynb #7696fa61
from ..ordering import out_of_order, in_order
def minmax_element(seq, first, last):
    """
    Returns the index of the minimum and maximum elements in the range [first, last).
    """
    if first == last:
        return last, last
    lo = hi = first
    for i in range(first + 1, last):
        if out_of_order(seq[lo], seq[i]):
            lo = i
        if in_order(seq[hi], seq[i]):
            hi = i
    return lo, hi

# %% ../../nbs/02_sequences/04_sorting/02_insertion-point.ipynb #b67f204b
from .find import find_adjacent_mismatch
from ..ordering import in_order

def is_sorted_until(a, first, last):
    """
    Returns the end of the longest sorted prefix of [first, last).
    """
    return find_adjacent_mismatch(a, first, last, in_order)

# %% ../../nbs/02_sequences/04_sorting/02_insertion-point.ipynb #7530dd98
def is_sorted(a, first, last):
    """
    Returns whether [first, last) is sorted.
    """
    return is_sorted_until(a, first, last) == last

# %% ../../nbs/02_sequences/04_sorting/02_insertion-point.ipynb #46a428fd
from ..ordering import out_of_order

def lower_bound(a, first, last, value):
    """
    Returns the first index in [first, last) where value may be inserted.
    """
    while first != last:
        middle = first + (last - first) // 2
        if out_of_order(value, a[middle]):  # a[middle] < value
            first = middle + 1
        else:
            last = middle
    return first

# %% ../../nbs/02_sequences/04_sorting/02_insertion-point.ipynb #865adef4
from ..ordering import out_of_order

def upper_bound(a, first, last, value):
    """
    Returns the first index in [first, last) after value.
    """
    while first != last:
        middle = first + (last - first) // 2
        if out_of_order(a[middle], value):  # value < a[middle]
            last = middle
        else:
            first = middle + 1
    return first

# %% ../../nbs/02_sequences/04_sorting/02_insertion-point.ipynb #2ae56efd
def equal_range(a, first, last, value):
    """
    Returns the indexes of the slice equivalent to value.
    """
    left = lower_bound(a, first, last, value)
    right = upper_bound(a, left, last, value)
    return left, right

# %% ../../nbs/02_sequences/04_sorting/02_insertion-point.ipynb #7bd6bd12
from bisect import bisect_left
from ..ordering import in_order
def binary_search(a, first, last, value):
    """
    Returns whether [first, last) contains a value equivalent to value.
    """
    i = lower_bound(a, first, last, value)
    # i = bisect_left(a, value, first, last)
    return i != last and in_order(a[i], value)

# %% ../../nbs/02_sequences/04_sorting/03_sort-101.ipynb #f5f2200b
from .rearrange import swap
from .sort import min_element, is_sorted

def selection_sort(a, first, last):
    for i in range(first, last):
        m = min_element(a, i, last)
        if m != i:
            swap(a, i, m)

# %% ../../nbs/02_sequences/04_sorting/03_sort-101.ipynb #bb2404a4
from .rearrange import rotate
from bisect import bisect_right
def insertion_sort(a, first, last):
    for i in range(first + 1, last):
        at = bisect_right(a, a[i], first, i)
        if at != i:
            rotate(a, at, i, i + 1)