# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02_sequences/04_sorting/02_insertion-point.ipynb.

# %% auto #0
__all__ = ['is_sorted_until', 'is_sorted', 'lower_bound', 'upper_bound', 'equal_range', 'binary_search']

# %% ../../nbs/02_sequences/04_sorting/02_insertion-point.ipynb #b67f204b
from .find import find_adjacent_mismatch
from ..ordering import in_order

def is_sorted_until(a, first, last):
    """
    Returns the end of the longest sorted prefix of [first, last).
    """
    return find_adjacent_mismatch(a, first, last, in_order)

# %% ../../nbs/02_sequences/04_sorting/02_insertion-point.ipynb #7530dd98
def is_sorted(a, first, last):
    """
    Returns whether [first, last) is sorted.
    """
    return is_sorted_until(a, first, last) == last

# %% ../../nbs/02_sequences/04_sorting/02_insertion-point.ipynb #46a428fd
from ..ordering import out_of_order

def lower_bound(a, first, last, value):
    """
    Returns the first index in [first, last) where value may be inserted.
    """
    while first != last:
        middle = first + (last - first) // 2
        if out_of_order(value, a[middle]):  # a[middle] < value
            first = middle + 1
        else:
            last = middle
    return first

# %% ../../nbs/02_sequences/04_sorting/02_insertion-point.ipynb #865adef4
from ..ordering import out_of_order

def upper_bound(a, first, last, value):
    """
    Returns the first index in [first, last) after value.
    """
    while first != last:
        middle = first + (last - first) // 2
        if out_of_order(a[middle], value):  # value < a[middle]
            last = middle
        else:
            first = middle + 1
    return first

# %% ../../nbs/02_sequences/04_sorting/02_insertion-point.ipynb #2ae56efd
def equal_range(a, first, last, value):
    """
    Returns the indexes of the slice equivalent to value.
    """
    left = lower_bound(a, first, last, value)
    right = upper_bound(a, left, last, value)
    return left, right

# %% ../../nbs/02_sequences/04_sorting/02_insertion-point.ipynb #7bd6bd12
from bisect import bisect_left
from ..ordering import in_order
def binary_search(a, first, last, value):
    """
    Returns whether [first, last) contains a value equivalent to value.
    """
    # i = lower_bound(a, first, last, value)
    i = bisect_left(a, value, first, last)
    return i != last and in_order(a[i], value)
