"""Docs: https://gophry.github.io/programming-first-principles/02_sequences/sorting.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02_sequences/11_sorting.ipynb.

# %% auto #0
__all__ = ['min_element', 'max_element', 'minmax_element']

# %% ../../nbs/02_sequences/11_sorting.ipynb #8c857822
from ..ordering import out_of_order

def min_element(a, first, last):
    """
    Returns the index of the minimum element in the range [first, last).
    """
    if first == last:
        return last
    min_index = first
    for i in range(first + 1, last):
        if out_of_order(a[min_index],a[i]):
            min_index = i
    return min_index

# %% ../../nbs/02_sequences/11_sorting.ipynb #da15b958
from ..ordering import in_order
def max_element(a, first, last):
    """ 
    Returns the index of the maximum element in the range [first, last).
    """
    if first == last:
        return last
    max_index = first
    for i in range(first + 1, last):
        if in_order(a[max_index],a[i]):
            max_index = i
    return max_index

# %% ../../nbs/02_sequences/11_sorting.ipynb #7696fa61
def minmax_element(a, first, last):
    """
    Returns the index of the minimum and maximum elements in the range [first, last).
    """
    if first == last:
        return last, last
    lo = hi = first
    for i in range(first + 1, last):
        if out_of_order(a[lo], a[i]):
            lo = i
        if in_order(a[hi], a[i]):
            hi = i
    return lo, hi
