"""Docs: https://gophry.github.io/programming-first-principles/helpers/predicates.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/helpers/predicates.ipynb.

# %% auto #0
__all__ = ['above_35', 'below_35', 'below_5000', 'is_even', 'is_odd', 'sums_to', 'amounts_sum_to']

# %% ../../nbs/helpers/predicates.ipynb #3db8d9ca
def above_35(score):
    """Return whether score is 35 or higher."""
    return score >= 35

def below_35(score):
    """Return whether score is 35 or lower."""
    return score <= 35

def below_5000(score):
    return score < 5000


# %% ../../nbs/helpers/predicates.ipynb #f14b9a7a
def is_even(x):
    """Return whether x is divisible by 2."""
    return x % 2 == 0

def is_odd(x):
    """Return whether x is not divisible by 2."""
    return x % 2 != 0

# %% ../../nbs/helpers/predicates.ipynb #51033388
def sums_to(*values, T):
    """Return whether the sum of values equals T."""
    return sum(values) == T

# %% ../../nbs/helpers/predicates.ipynb #ffe24e6e
from ..predicates import sums_to
def amounts_sum_to(*txns, T):
    """Return whether these are different transactions whose amounts sum to T."""
    amounts = [t.amount for t in txns]
    return len({t.id for t in txns}) == len(txns) and sums_to(*amounts, T=T)
