"""Docs: https://gophry.github.io/programming-first-principles/helpers/variables.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/helpers/variables.ipynb.

# %% auto #0
__all__ = ['scores_out_of_100', 'scores', 'generate_scores']

# %% ../../nbs/helpers/variables.ipynb #b48eb583
scores_out_of_100 = (40, 10, 35, 5, 80, 75, 5, 80)

# %% ../../nbs/helpers/variables.ipynb #96d5b772
import random
from pprint import pprint
def generate_scores():
    scores = [random.randint(1, 100) for _ in range(100)]
    random.shuffle(scores)
    return scores
# pprint(generate_scores,compact=True, width=80)

# %% ../../nbs/helpers/variables.ipynb #09bb1e6f
scores = (18, 91, 92, 35, 10, 35, 40, 80, 30, 26, 95, 39, 50, 14, 63, 92, 32, 44, 30, 43,
 100, 6, 63, 3, 42, 88, 67, 92, 34, 10, 96, 85, 23, 7, 86, 80, 13, 58, 13, 59,
 42, 94, 28, 72, 9, 46, 28, 97, 59, 47, 93, 47, 94, 75, 12, 67, 48, 64, 6, 66,
 61, 56, 72, 4, 8, 1, 41, 75, 62, 16, 2, 73, 32, 52, 82, 14, 54, 15, 37, 53, 14,
 96, 16, 14, 42, 77, 62, 68, 68, 40, 19, 95, 66, 29, 41, 22, 1, 25, 50, 32)
