# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_sequences/06_cost-complexity.ipynb.

# %% auto #0
__all__ = ['c_sum', 'c_min', 'c_max', 'find_fraud_2sum', 'find_fraud_3sum']

# %% ../nbs/02_sequences/06_cost-complexity.ipynb #fcb3ddfe
def c_sum(nums):
  sum = 0
  for num in nums:
    sum += num
  return sum

# %% ../nbs/02_sequences/06_cost-complexity.ipynb #86d25f31
def c_min(seq):
  #Iterator to walk over the sequence
  it = iter(seq)
  cmp = 0
  # Assume first element as min
  winner = next(it)
  # walk over rest to compare
  for val in it:
    cmp += 1
    if val < winner:
      winner = val
  return winner, cmp

# %% ../nbs/02_sequences/06_cost-complexity.ipynb #e861efe1
def c_max(seq):
  #Iterator to walk over the sequence
  it = iter(seq)
  cmp = 0
  # Assume first element as min
  winner = next(it)
  # walk over rest to compare
  for val in it:
    cmp+=1
    # if not out_of_order(winner,val):
    if not val < winner:
      winner = val
  return winner, cmp

# %% ../nbs/02_sequences/06_cost-complexity.ipynb #cddf3ade
def find_fraud_2sum(txns, T):
  cmp = 0
  l = len(txns)
  for t1 in txns:
    for t2 in txns:
      cmp += 1
      if t1.id != t2.id and t1.amount + t2.amount == T:
        return (t1,t2),(l,cmp)
  return (None,None),(l,cmp)


# %% ../nbs/02_sequences/06_cost-complexity.ipynb #c80c245e
def find_fraud_3sum(txns, T):
    cmp = 0
    l = len(txns)
    for t1 in txns:
        for t2 in txns:
            for t3 in txns:
                cmp += 1
                ids = {t1.id, t2.id, t3.id}
                if len(ids) == 3 and t1.amount + t2.amount + t3.amount == T:
                    return (t1, t2, t3), (l, cmp)
    return (None, None, None), (l, cmp)
