# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_sequences/03_algorithms-101/01_cost-complexity.ipynb.

# %% auto #0
__all__ = ['c_sum', 'c_min', 'c_max', 'find_2sum', 'find_3sum']

# %% ../nbs/02_sequences/03_algorithms-101/01_cost-complexity.ipynb #fcb3ddfe
def c_sum(nums):
  sum = 0
  for num in nums:
    sum += num
  return sum

# %% ../nbs/02_sequences/03_algorithms-101/01_cost-complexity.ipynb #86d25f31
def c_min(seq):
  #Iterator to walk over the sequence
  it = iter(seq)
  # Assume first element as min
  winner = next(it)
  # walk over rest to compare
  for val in it:
    if val < winner:
      winner = val
  return winner

# %% ../nbs/02_sequences/03_algorithms-101/01_cost-complexity.ipynb #e861efe1
def c_max(seq):
  #Iterator to walk over the sequence
  it = iter(seq)
  # Assume first element as min
  winner = next(it)
  # walk over rest to compare
  for val in it:
    if not val < winner:
      winner = val
  return winner

# %% ../nbs/02_sequences/03_algorithms-101/01_cost-complexity.ipynb #66cae068
from .predicates import sums_to
def find_2sum(a, T, pred=sums_to):
    for x in a:
        for y in a:
            if pred(x, y, T=T):
                return x, y
    return None, None

# %% ../nbs/02_sequences/03_algorithms-101/01_cost-complexity.ipynb #c80c245e
from .predicates import sums_to
def find_3sum(a, T, pred=sums_to):
    for x in a:
        for y in a:
            for z in a:
                if pred(x, y, z, T=T):
                    return x, y, z
    return None, None, None
