"""Docs: https://gophry.github.io/programming-first-principles/02_sequences/01_arrays/array.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_sequences/01_arrays/01_array.ipynb.

# %% auto #0
__all__ = ['my_array']

# %% ../nbs/02_sequences/01_arrays/01_array.ipynb #4e48b20a
from array import array
my_array = array("i",[501, 502, 503, 504, 505])
