"""Docs: https://gophry.github.io/programming-first-principles/index.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/index.ipynb.

# %% auto #0
__all__ = ['prepare_notebook']

# %% ../nbs/index.ipynb #d8831190
def prepare_notebook():
    ip = get_ipython()
    if ip is None: return
    from IPython.core.interactiveshell import InteractiveShell
    InteractiveShell.ast_node_interactivity = "all"
    # ip.user_ns.update()
