"""Docs: https://gophry.github.io/programming-first-principles/index.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/index.ipynb.

# %% auto #0
__all__ = ['prepare_notebook']

# %% ../nbs/index.ipynb #d8831190
def prepare_notebook():
    ip = get_ipython()
    if ip is None: return
    from IPython.core.interactiveshell import InteractiveShell
    from array import array
    from pprint import pprint
    from wigglystuff import LiveEdit
    import operator
    from functools import partial 
    import matplotlib.pyplot as plt
    from collections import namedtuple
    import random, copy 
    import ctypes
    import sys
    from ipaddress import IPv4Address
    from typing import Sequence
    import numpy as np
    import inspect
    InteractiveShell.ast_node_interactivity = "all"
    ip.user_ns.update(
        array=array, 
        pprint=pprint, 
        LiveEdit=LiveEdit, 
        operator=operator, 
        partial=partial, 
        plt=plt,
        namedtuple=namedtuple,
        random=random,
        copy=copy,
        ctypes=ctypes,
        sys=sys,
        IPv4Address=IPv4Address,
        Sequence=Sequence,
        np=np,
        inspect=inspect
    )
