"""Docs: https://gophry.github.io/programming-first-principles/02_sequences/03_algorithms-101/ordering.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_sequences/03_algorithms-101/05_ordering.ipynb.

# %% auto #0
__all__ = ['out_of_order', 'in_order']

# %% ../nbs/02_sequences/03_algorithms-101/05_ordering.ipynb #df4e4f31
def out_of_order(x, y):
    return y < x              # second < first

def in_order(x, y):
    return not out_of_order(x, y)
