# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/helpers/predicates.ipynb.

# %% auto #0
__all__ = ['above_35', 'below_35', 'is_even', 'is_odd']

# %% ../nbs/helpers/predicates.ipynb #3db8d9ca
def above_35(score):
    return score >= 35

def below_35(score):
    return score <= 35

# %% ../nbs/helpers/predicates.ipynb #f14b9a7a
def is_even(x):
    return x % 2 == 0

def is_odd(x):
    return x % 2 != 0
